name: word_maker
description: "Computer Science Semestral Project"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  path_provider: ^2.0.2
  image_picker: ^1.1.1
  google_fonts: ^6.2.1
  diacritic: ^0.1.5
  shared_preferences: ^2.2.3
  postgres: ^3.2.1
  hive: ^2.2.3
  provider: ^6.1.2
  hive_flutter: ^1.1.0
  http_io: ^1.2.0
  url_launcher: ^6.2.6
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets\images\no_image.png
    - assets\images\Letters.png
    - assets\images\Buttons.png
    - assets\images\WordList.png
    - assets\animations\confetti.json
  uses-material-design: true
