CREATE DATABASE WordMaker

CREATE TABLE tbLanguages (
    LanguageId INT PRIMARY KEY IDENTITY(1,1),
    LanguageCode VARCHAR(10) NOT NULL UNIQUE,
    LanguageName VARCHAR(50) NOT NULL
);

CREATE TABLE tblWords (
    WordId INT PRIMARY KEY IDENTITY(1,1),
    Word VARCHAR(255) NOT NULL,
    WordDefinition TEXT,
    WordExample TEXT,
	LanguageId INT NOT NULL,
    FOREIGN KEY (LanguageId) REFERENCES tbLanguages(LanguageId)
);

CREATE TABLE tbAdmins (
    AdminID INT PRIMARY KEY IDENTITY(1,1),
    AdminFullName NVARCHAR(255) NOT NULL,
	AdminCorporateEmail NVARCHAR(255) NOT NULL,
	AdminPhoneNumber NVARCHAR(255) NOT NULL,
	AdminPrivilegeLevel NVARCHAR(1) NOT NULL,
	AdminLogin NVARCHAR(255) NOT NULL,
	AdminPassword NVARCHAR(255) NOT NULL,
);

CREATE TABLE tbUsers (
    UserID INT PRIMARY KEY IDENTITY(1,1),
    UserName NVARCHAR(255) NOT NULL,
	UserPassword NVARCHAR(255) NOT NULL,
	UserEmail NVARCHAR(255) NOT NULL,
	UserLevel NVARCHAR(255) NOT NULL,
	UserPoints NVARCHAR(255) NOT NULL
);